-- Import the remaining public posts from the former PCA Youth Center blog.
-- Text, dates, authors, covers, and inline-image ordering are preserved from
-- the server-rendered legacy pages; images are served as local static assets.

insert into public.blog_posts (
    slug, title, excerpt, content_version, content,
    cover_image_source, cover_image_path, cover_image_alt,
    status, author_user_id, author_display_name, published_at, created_at, updated_at
)
values
(
    '2024-induction-day',
    '2024 Induction Day',
    'August 18th marks the start of a new year for PCA Youth Center. PCA Youth Center members, both new and returning, gathered at North Park for induction day, an enjoyable two hours of introductions and team bonding between the members of the 2024-2025 youth student council.',
    1,
    $content$[{"type":"paragraph","text":"August 18th marks the start of a new year for PCA Youth Center. PCA Youth Center members, both new and returning, gathered at North Park for induction day, an enjoyable two hours of introductions and team bonding between the members of the 2024-2025 youth student council."},{"type":"paragraph","text":"After the day started with an invigorating speech from the student council president and a brief introduction from the other position holding members, members gathered in the field to participate in an exciting round of the sandwich game, a game where each member says their name and adds an ingredient to the imaginary sandwich. Moving across the circle, each member recites the previous members’ names and corresponding sandwich ingredients before adding their own ingredient. Despite many forgotten ingredients, most members successfully learned most names."},{"type":"paragraph","text":"After adding some twists, like reciting the names and ingredients backward, the student council moved on to throwing a ball toward one another. In order to further help retain members’ names, the thrower had to address the receiver by their name."},{"type":"paragraph","text":"Next was a game similar to the concept of speed dating, where each person meets up with another member and gives a short introduction before moving on to another person after a minute. Conversation flowed as each member met their future fellow student council members and began to bond."},{"type":"paragraph","text":"Wrapping up the day was a classic, timeless game: Uno. Armed with eight decks of Uno cards, the student council split into three groups organized by grade level and cards were quickly dealt. The chatter continued as members munched on chips while trying their luck with wilds and reverses. PCA shirts were sold to new members as the games came to an end."},{"type":"paragraph","text":"The thrilling day concluded with a farewell speech from the president and information about the next upcoming meeting. PCA can’t wait to see all the new possibilities and opportunities this new year will bring!"}]$content$::jsonb,
    'local',
    'images/blog/2024-induction-day-cover.avif',
    '2024 Induction Day',
    'published',
    null,
    'Joanna Bi',
    '2024-09-07T18:15:47.858Z'::timestamptz,
    '2024-09-07T18:15:47.858Z'::timestamptz,
    '2024-09-07T18:15:47.858Z'::timestamptz
),
(
    'career-talk',
    'Career Talk',
    'During the Career Talk Event, we heard from four different presenters. They gave us important advice for our future self. It was a fascinating event because we learned about how to encounter challenges and embrace change.',
    1,
    $content$[{"type":"paragraph","text":"During the Career Talk Event, we heard from four different presenters. They gave us important advice for our future self. It was a fascinating event because we learned about how to encounter challenges and embrace change."},{"type":"paragraph","text":"Before we had this big event, we had to try and find ways to advertise on social media and talk to different schools about this event. The Social Media Team was able to create a poster and caption to post on Instagram. PCA also tried to advertise Career Talk to different school districts. Different PCA students were assigned to send an email to advertise Career Talk to each school. Many parents on WeChat were able to post and share this poster around their stories. PCA had to create a zoom meeting where the event would take place. We also sent thank you letters to the presenters for being able to join and talk with us."},{"type":"paragraph","text":"PCA had a blast listening to the presenters and learning loads of information during this event. Some takeaways from the two days of presenting were, “Failure is just a redirection, don’t give up.” We heard this from our wonderful speaker, Leonela Pascual. Another takeaway we heard from Yuan Tao was, “GPA and IQ will get you to a good position, but your attitude and connections are what will get you farther.” Helen Feinstein told us, “You did what you thought was best at the time.” The final takeaway from this event is from Annie Cui, “You do it for yourself and it’s all in your name.” We have heard some inspirational messages during this event which will help push many kids in the future."},{"type":"paragraph","text":"PCA is very grateful for all the people who signed up to listen to each presenter's talk. We want to thank the presenters for joining us because they are busy people. This event went really well and PCA will be definitely thinking about doing this next year!"}]$content$::jsonb,
    'local',
    'images/blog/career-talk-cover.avif',
    'Career Talk',
    'published',
    null,
    'Hanna Qian',
    '2024-01-22T03:58:35.637Z'::timestamptz,
    '2024-01-22T03:58:35.637Z'::timestamptz,
    '2024-01-22T03:58:35.637Z'::timestamptz
),
(
    'pca-fall-art-show',
    'PCA Fall Art Show',
    'With fall in the air, PCA held its annual art show at the Mount Lebanon Library for an afternoon filled with fun, excitement, and most importantly, beautiful art! A variety of activities were offered to make the event enjoyable for all ages, such as free drawing. A blind drawing activity was also...',
    1,
    $content$[{"type":"paragraph","text":"With fall in the air, PCA held its annual art show at the Mount Lebanon Library for an afternoon filled with fun, excitement, and most importantly, beautiful art! A variety of activities were offered to make the event enjoyable for all ages, such as free drawing. A blind drawing activity was also held where two partners put their cooperation and communication skills to the test. The drawer was blindfolded while the other gave directions. PCA members also drew arm paintings on participants, which was a big hit! One of the highlights of the event was the collaborative painting. Each person was given a small tile that they could personalize and glue onto the painting. With each person contributing to the painting, the result was an intricate painting that truly was special! The son of Hedy O’Biel, who is known for her expressive abstract paintings and two-time winner of the Jackson Pollock-Lee Krasner Foundation Award, spoke at the event. He shared with everyone a piece from her titled “Strength” and called on the audience for their personal interpretations on the meaning of the piece. Overall, the event was a success, emphasizing the deep impact that different forms of art can have."},{"type":"paragraph","text":"Check out Hedy’s amazing art here! https://www.hedyobeilart.com/"},{"type":"paragraph","text":"Created by: Angie Sun, Angelina Li, Andrew Li"}]$content$::jsonb,
    'local',
    'images/blog/pca-fall-art-show-cover.avif',
    'PCA Fall Art Show',
    'published',
    null,
    'liandrew2025',
    '2023-12-04T02:38:58.016Z'::timestamptz,
    '2023-12-04T02:38:58.016Z'::timestamptz,
    '2023-12-04T02:38:58.016Z'::timestamptz
),
(
    'pca-mid-autumn-festival',
    'PCA Mid-Autumn Festival',
    'Happy Fall! PCA held its Mid-Autumn festival this weekend at Mt.Lebo for the 2nd year with many fun activities and snacks! The Mid-Autumn Festival promotes Chinese history and culture. The holiday takes place every year on the 29th of September with huge celebrations. It is traditional to hang co...',
    1,
    $content$[{"type":"paragraph","text":"Happy Fall! PCA held its Mid-Autumn festival this weekend at Mt.Lebo for the 2nd year with many fun activities and snacks! The Mid-Autumn Festival promotes Chinese history and culture. The holiday takes place every year on the 29th of September with huge celebrations. It is traditional to hang colorful lanterns and eat delicious mooncakes. There were lanterns for sale that you could also decorate and personalize, which symbolize good fortune in Chinese culture. There were also mooncakes, a classic Chinese sweet treat."},{"type":"paragraph","text":"With various activities throughout the event, there was something for everyone! There was face painting, lanterns you could make and personalize with stickers, paints, letters, etc., paper cutting of all sorts of traditional pictures and patterns, and even air dry clay for guests to make clay sculptures with! Many parents came with their kids and said that it was a very fun experience and the kids loved socializing. In addition to the activities, many kids also enjoyed playing on the playground nearby."},{"type":"paragraph","text":"This event was a success, with lots of people showing up to attend! It was all smiles and laughter as PCA celebrated this monumental holiday and welcomed the new season."},{"type":"paragraph","text":"Written by : Angelina Li"}]$content$::jsonb,
    'local',
    'images/blog/pca-mid-autumn-festival-cover.avif',
    'PCA Mid-Autumn Festival',
    'published',
    null,
    'liandrew2025',
    '2023-10-06T11:46:19.678Z'::timestamptz,
    '2023-10-06T11:46:19.678Z'::timestamptz,
    '2023-10-06T11:46:19.678Z'::timestamptz
),
(
    'cultural-festival-1',
    'Cultural Festival',
    'The Chinese Cultural Festival at Mellon Park is where all the fun happened and delicious food was. The PCA gathered everyone together to do many activities such as face painting and making bookmarks.',
    1,
    $content$[{"type":"paragraph","text":"The Chinese Cultural Festival at Mellon Park is where all the fun happened and delicious food was. The PCA gathered everyone together to do many activities such as face painting and making bookmarks."},{"type":"paragraph","text":"Some background information of the Cultural Festival, its history and where it takes place every year. The Cultural Festival is an annual event in the Pittsburgh Chinese Cultural Center, or PCCC, and it is also the biggest annual event held in the Pittsburgh Chinese Community. It started in 2015, which means that it has been going on for eight years. It is usually a whole day event that would operate from 11 AM to 6 PM. The festival has an expected amount of five thousand people to join this event each year. Some activities for this festival include music and dance performances, eating Asian cuisine, and playing fun outdoor games."},{"type":"paragraph","text":"The PCA’s time at the Cultural Festival was a huge success, with more than enough volunteers able to help with different activities. As we asked the parents around us, they answered as it was an overall ten out of ten experience. There were amazing performances including Chinese dances, festive music, and yummy food. PCA had an exciting time at Mellon Park, and cannot wait to come back for next year's Chinese Cultural Festival!"},{"type":"paragraph","text":"PCA had a wonderful time with the Chinese Cultural Festival, as all members were able to help out and have fun! During the festival, we shared the culture and spread kindness to all the people."},{"type":"paragraph","text":"Blog Written By: Hannah Qian"}]$content$::jsonb,
    'local',
    'images/blog/cultural-festival-1-cover.avif',
    'Cultural Festival',
    'published',
    null,
    'liandrew2025',
    '2023-09-23T14:52:54.585Z'::timestamptz,
    '2023-09-23T14:52:54.585Z'::timestamptz,
    '2023-09-23T14:52:54.585Z'::timestamptz
),
(
    'pca-induction-day',
    'PCA Induction Day',
    'With a new year rolling around for PCA Youth Center, North Park’s Olympia Shelter was the place to be with Induction Day and Orientation! The 2023-2024 Student Council gathered together to do introductions, team building and bonding.',
    1,
    $content$[{"type":"paragraph","text":"With a new year rolling around for PCA Youth Center, North Park’s Olympia Shelter was the place to be with Induction Day and Orientation! The 2023-2024 Student Council gathered together to do introductions, team building and bonding."},{"type":"paragraph","text":"To kick off the first event of the year, our new leadership board introduced themselves and everything they could expect and look forward to in the exciting year ahead. New members proceeded to introduce themselves, taking the first step in their journey of becoming an integral part of PCA. Icebreaker activities followed right after, starting with the sandwich game, where everyone said their name and a topping they would add to our hypothetical group PCA sandwich, with each person progressively reciting all the previous people's names and toppings. Afterward, the whole group played a few rounds of duck-duck-goose, using each other’s names as replacement for the word “duck”."},{"type":"paragraph","text":"Not long after, the big group then split into their respective teams, Outreach and Events Planning, where both furthered their in-depth introductions and team building with one-minute elevator pitches, and Outreach went on a short hike through beautiful North Park for continued team bonding. Finally, the two teams regrouped and joined together for some pictures and a potluck of shrimp, watermelon, cookies and many other delicacies to bring an exciting induction day to a close!"},{"type":"paragraph","text":"PCA had an extremely successful first day and event of the new year, with first year members learning the ins and outs of what to expect this year with PCA and team bonding between everyone! Keep an eye out for events coming in the future; we are looking forward to another amazing year with PCA!"},{"type":"paragraph","text":"Blog written by: Angelina Li, Andrew Li, Angie Sun, and Lydia Tang"}]$content$::jsonb,
    'local',
    'images/blog/pca-induction-day-cover.avif',
    'PCA Induction Day',
    'published',
    null,
    'liandrew2025',
    '2023-08-21T04:00:00.000Z'::timestamptz,
    '2023-08-21T04:00:00.000Z'::timestamptz,
    '2023-08-21T04:00:00.000Z'::timestamptz
),
(
    'summer-field-day-blog',
    'Summer Field Day Blog',
    'With the arrival of summer, the PCA Student Council held an interactive and engaging field day event on the afternoon of Saturday, June 17th.',
    1,
    $content$[{"type":"paragraph","text":"With the arrival of summer, the PCA Student Council held an interactive and engaging field day event on the afternoon of Saturday, June 17th."},{"type":"paragraph","text":"The activities planned consisted of different stations with four rotations. These involved chopsticks, water transferring, squat lines, and a fun relay race. The chopsticks station aimed to heighten the competitive spirits, concentration, and precision of the kids as they utilized chopsticks to try to move jellybeans from plate to plate. Meanwhile at the water transfer station, the kids were able to spend their energy by racing back and forth with buckets of water, having an exhilarating time with more friendly competition. They were able to warm up their bodies by having a moment to do squats, in which their determination to win was fueled by the prospect of an exciting reward. Finally, the last rotation was a thrilling relay race, which consisted of a quick game of ring toss, rock paper scissors with their legs, sone spinning, and a contest to travel while balance ping pong balls on spoons, wrapping up with the kids eagerly racing all the way back to the start."},{"type":"paragraph","text":"After the stations had concluded, next came the big group events. The games involved were freeze tag, a race to collect ribbons, and finally, with much anticipation—water balloons! Each kid had an exciting time while also working themselves to do their best at each event; especially so when the time came for them to get ahold of the water balloons. This was noticeably favored by many of the kids, who participated with great enthusiasm and excitement."},{"type":"paragraph","text":"Overall, the event was successful and fun for the participants and the council! The kids were able to warm up to the coming of summer together with a series of exhilarating competitions and activities, and additionally making new memories with one another."},{"type":"paragraph","text":"Lastly, we would like to congratulate the student council members that won Presidential Volunteer Awards this year. Each member who hit 50+ hours within the span of the year was able to receive a certificate and medal to celebrate their leadership and hard work!"},{"type":"paragraph","text":"Written by: Joanna Bi"}]$content$::jsonb,
    'local',
    'images/blog/summer-field-day-blog-cover.avif',
    'Summer Field Day Blog',
    'published',
    null,
    'Colin Liang',
    '2023-06-26T17:34:15.235Z'::timestamptz,
    '2023-06-26T17:34:15.235Z'::timestamptz,
    '2023-06-26T17:34:15.235Z'::timestamptz
),
(
    'aapi-workshop',
    'AAPI Workshop',
    'To celebrate AAPI Month, on Saturday May 13th, the PCA Youth Center organized a workshop for the Eastern Pittsburgh community in Murrysville.',
    1,
    $content$[{"type":"paragraph","text":"To celebrate AAPI Month, on Saturday May 13th, the PCA Youth Center organized a workshop for the Eastern Pittsburgh community in Murrysville."},{"type":"paragraph","text":"The event was held at the Murrysville Community Library as a walk-in event for all ages. There were a total of four stations that many participants were enthusiastic about. These included paper cutting, origami, face and arm painting, and water calligraphy."},{"type":"paragraph","text":"At the paper cutting stations, participants were instructed by a student council member on how to trace, cut, glue, and decorate rabbits. As this current year is the year of the rabbit, many of the stations centered around this theme. There was some difficulty in cutting the paper for the younger children, especially because it was so thin, but their parents were there to help them, and they cheerfully completed their bunnies."},{"type":"paragraph","text":"Right beside the paper cutting station was the origami station. At this station, participants were taught how to fold an origami rabbit. The rabbit proved to be somewhat difficult, even for adults, so other options like butterflies and swans were also offered."},{"type":"paragraph","text":"The kids anticipated the face and arm painting station the most, excitedly hopping up and down while waiting. A variety of designs were offered, with many participants getting multiple. These designs included a rabbit, panda, a Chinese lantern, and some Chinese characters. The most popular was the rabbit, followed by the panda, but some participants requested designs like their favorite TV show character, which our student council member graciously painted for them."},{"type":"paragraph","text":"At the water calligraphy station, participants traced Chinese characters with water on a special paper. Many also opted to draw their own designs, and this was completely fine because of the paper."},{"type":"paragraph","text":"Participants really enjoyed this event, and with the cooperation of the Murrysville Library, the event and its advertising was successful. Along with the participants, we also had a wonderful experience, so in the future, we plan on hosting more fun and educational events there!"}]$content$::jsonb,
    'local',
    'images/blog/aapi-workshop-cover.avif',
    'AAPI Workshop',
    'published',
    null,
    'Grace Huang',
    '2023-05-29T00:23:13.417Z'::timestamptz,
    '2023-05-29T00:23:13.417Z'::timestamptz,
    '2023-05-29T00:23:13.417Z'::timestamptz
),
(
    'd-i-v-e',
    'D.I.V.E',
    'Last week, PCA was excited to host our Design, Invent, Visualize, Experiment (D.I.V.E.) workshop at the Upper Saint Clair Library! In this event, participants had the opportunity to explore different aspects of science through various interactive experiments. We conducted labs such as a bridge bu...',
    1,
    $content$[{"type":"paragraph","text":"Last week, PCA was excited to host our Design, Invent, Visualize, Experiment (D.I.V.E.) workshop at the Upper Saint Clair Library! In this event, participants had the opportunity to explore different aspects of science through various interactive experiments. We conducted labs such as a bridge building experiment, creating a catapult, hosting a cardstock boat race, and many more."},{"type":"paragraph","text":"To begin their activities, each participant was able to construct a catapult using popsicle sticks, rubber bands, and a spoon. The children particularly enjoyed putting their creations to the test by launching catapults."},{"type":"paragraph","text":"In the tin foil boat event, participants built their own boat designs using a square of aluminum foil. They then competed to see whose boat could carry the most coins without sinking. Through this competition, they learned about gravity, buoyancy, and surface tension while working with water and making sure their boats stayed afloat."},{"type":"paragraph","text":"Another material that could be used to make boats is cardstock. In this event, the participants had to fold a paper boat out of cardstock and test them in water. They then put dish soap behind the ships, which propelled the paper creations forward."},{"type":"paragraph","text":"After testing their boats, the participants used uncooked pasta noodles and marshmallows to build a bridge. The result was a fun experience playing with food and some innovative bridges as well. The attendees learned about which shapes were geometrically best for building, as well as being able to see them in real-world applications."},{"type":"paragraph","text":"Next, the participants learned how to make invisible ink. They painted designs and words on paper with lemon juice. Then, they heated the paper to reveal the secret messages they had made. As the lemon juice heats up, it undergoes an oxidation reaction and darkens, revealing the hidden message. Now, they can pass notes in class without being caught!"},{"type":"paragraph","text":"Through these interactive exercises, we demonstrated important skills such as creating blueprint designs and introduced participants to aspects of civil and transportation engineering. Overall, the series of experiments provided a wonderful opportunity for participants to gain an understanding of design, innovation, and science. We would like to thank all the volunteers and participants who made this event possible. Stay tuned for future events!"}]$content$::jsonb,
    'local',
    'images/blog/d-i-v-e-cover.avif',
    'D.I.V.E',
    'published',
    null,
    'Colin Liang',
    '2023-05-01T00:14:37.561Z'::timestamptz,
    '2023-05-01T00:14:37.561Z'::timestamptz,
    '2023-05-01T00:14:37.561Z'::timestamptz
),
(
    'coding-workshop-2023',
    'Coding Workshop 2023',
    'Recently, the PCA Youth Center organized a coding workshop to introduce aspiring students to programming in Python and Javascript. Over the course of a few hours, the nearly 40 kids developed a foundational understanding through a combination of direct teaching and hands-on projects.',
    1,
    $content$[{"type":"paragraph","text":"Recently, the PCA Youth Center organized a coding workshop to introduce aspiring students to programming in Python and Javascript. Over the course of a few hours, the nearly 40 kids developed a foundational understanding through a combination of direct teaching and hands-on projects."},{"type":"paragraph","text":"The Python group, taught by Aaron Peng and Darren Wang, worked through coding a magic 8 ball, mad libs, and the game higher lower. The students demonstrated their newfound knowledge of Python by adding their individual modifications to each program. After the workshop concluded, the students excitedly shared their projects with each other. By the end, the fun atmosphere and engaging projects had given the students a solid understanding of loops, if statements, and user input."},{"type":"paragraph","text":"Overall, this event received overwhelmingly positive feedback from both participants and volunteers. Thanks to all the volunteers who made this event possible!"}]$content$::jsonb,
    'local',
    'images/blog/coding-workshop-2023-cover.avif',
    'Coding Workshop 2023',
    'published',
    null,
    'Darren Wang',
    '2023-04-17T00:52:39.809Z'::timestamptz,
    '2023-04-17T00:52:39.809Z'::timestamptz,
    '2023-04-17T00:52:39.809Z'::timestamptz
),
(
    'community-garden-clean-up',
    'Community Garden Clean-Up',
    'With winter approaching, the PCA decided to help prepare for the coming spring by helping tidy up. Around 15 volunteers gathered at Herron Avenue Flower Garden, supporting the Western Pennsylvania Conservancy. The volunteers toiled in the pouring rain to help remove annual flowers and weeds. Than...',
    1,
    $content$[{"type":"paragraph","text":"With winter approaching, the PCA decided to help prepare for the coming spring by helping tidy up. Around 15 volunteers gathered at Herron Avenue Flower Garden, supporting the Western Pennsylvania Conservancy. The volunteers toiled in the pouring rain to help remove annual flowers and weeds. Thanks to all who came out and helped! We appreciate the continued effort to keep our community in great shape."}]$content$::jsonb,
    'local',
    'images/blog/community-garden-clean-up-cover.avif',
    'Community Garden Clean-Up',
    'published',
    null,
    'Colin Liang',
    '2022-11-14T01:37:49.853Z'::timestamptz,
    '2022-11-14T01:37:49.853Z'::timestamptz,
    '2022-11-14T01:37:49.853Z'::timestamptz
),
(
    'the-fall-mash-up',
    'Fall Mash-Up',
    'Fall has arrived! The PCA Youth Center celebrated the change of seasons with a Fall Mash Up event at Deer Browse Shelter 1 in North Park. Attendees participated in many different activities, such as a potato sack race and a scavenger hunt for candy. Best of all, the participants enjoyed painting...',
    1,
    $content$[{"type":"paragraph","text":"Fall has arrived! The PCA Youth Center celebrated the change of seasons with a Fall Mash Up event at Deer Browse Shelter 1 in North Park. Attendees participated in many different activities, such as a potato sack race and a scavenger hunt for candy. Best of all, the participants enjoyed painting pumpkins! Overall, the event was a blast! Thanks to all the volunteers who helped out and to all the contributors who supported our mission. Stay tuned for our next events!"}]$content$::jsonb,
    'local',
    'images/blog/the-fall-mash-up-cover.avif',
    'Fall Mash-Up',
    'published',
    null,
    'Aaron Jiang',
    '2022-10-17T00:26:11.142Z'::timestamptz,
    '2022-10-17T00:26:11.142Z'::timestamptz,
    '2022-10-17T00:26:11.142Z'::timestamptz
),
(
    'cultural-festival',
    'Cultural Festival',
    'To wrap up September, the PCA Youth participated in the Pittsburgh Chinese Cultural Festival held in Mellon Park. People who visited were able to browse the many booths that showcased Chinese culture through activities, food, and merchandise. The PCA Youth had our very own booth that allowed visi...',
    1,
    $content$[{"type":"paragraph","text":"To wrap up September, the PCA Youth participated in the Pittsburgh Chinese Cultural Festival held in Mellon Park. People who visited were able to browse the many booths that showcased Chinese culture through activities, food, and merchandise. The PCA Youth had our very own booth that allowed visitors to try out Chinese calligraphy or to purchase their own customizable bookmarks. We would like to thank all the volunteers who helped to run our booth and those who stopped by for supporting our mission. Make sure to keep an eye out for any of our future events!"}]$content$::jsonb,
    'local',
    'images/blog/cultural-festival-cover.avif',
    'Cultural Festival',
    'published',
    null,
    'Colin Liang',
    '2022-10-03T00:47:08.346Z'::timestamptz,
    '2022-10-03T00:47:08.346Z'::timestamptz,
    '2022-10-03T00:47:08.346Z'::timestamptz
),
(
    'mid-autumn-festival',
    'Mid-Autumn Festival',
    'With fall drawing ever closer, the PCA Youth Center held a Mid-Autumn Festival to celebrate the traditional Chinese holiday. The afternoon was filled with enthusiastic laughter as around 50 kids cycled through an array of exciting stations, which included hand painting, origami folding, lantern p...',
    1,
    $content$[{"type":"paragraph","text":"With fall drawing ever closer, the PCA Youth Center held a Mid-Autumn Festival to celebrate the traditional Chinese holiday. The afternoon was filled with enthusiastic laughter as around 50 kids cycled through an array of exciting stations, which included hand painting, origami folding, lantern painting, and shuttlecock juggling."},{"type":"paragraph","text":"During origami, kids learned how to fold different kinds of rabbits, such as bookmarks and even a standing one. At hand painting, participants could choose between various designs, such as a flower or the PCA logo."},{"type":"paragraph","text":"At the lantern painting station, kids demonstrated their creativity and imagination by creating vivid patterns and designs. Their colorful lanterns lit up the pavilion with further cheeriness."},{"type":"paragraph","text":"Overall, our event was a big success, spreading culture and festivity throughout the community. Kids of all ages were able to explore Chinese traditions while having a fun time."},{"type":"paragraph","text":"Finally, thank you to all the volunteers who took time out of their weekend to make this event possible. We would also like to express our gratitude to all the participants for supporting our cause. We hope you look forward to future events!"}]$content$::jsonb,
    'local',
    'images/blog/mid-autumn-festival-cover.avif',
    'Mid-Autumn Festival',
    'published',
    null,
    'Darren Wang',
    '2022-10-03T00:13:46.791Z'::timestamptz,
    '2022-10-03T00:13:46.791Z'::timestamptz,
    '2022-10-03T00:13:46.791Z'::timestamptz
),
(
    'mckeesport-area-food-distribution',
    'McKeesport Area Food Distribution',
    'With summer coming to a close, the PCA Youth Center participated in one last event before school started, a food distribution event hosted by the Greater Pittsburgh Community Food Bank.',
    1,
    $content$[{"type":"paragraph","text":"With summer coming to a close, the PCA Youth Center participated in one last event before school started, a food distribution event hosted by the Greater Pittsburgh Community Food Bank."},{"type":"paragraph","text":"The distribution took place at McKeesport Area Highschool, where 25 of our own participants worked together under the hot sun to provide a variety of fresh produce and other foods to many families in need."},{"type":"paragraph","text":"In the end, the event was a great success. The PCA Youth and our volunteers are glad to have impacted many people in our community and hope to do so again in the future. Thanks again to all of the organizers and participants who allowed us to carry this event out."}]$content$::jsonb,
    'local',
    'images/blog/mckeesport-area-food-distribution-cover.avif',
    'McKeesport Area Food Distribution',
    'published',
    null,
    'Colin Liang',
    '2022-09-05T00:43:49.463Z'::timestamptz,
    '2022-09-05T00:43:49.463Z'::timestamptz,
    '2022-09-05T00:43:49.463Z'::timestamptz
),
(
    'leadership-speaker-event',
    'Leadership Speaker Event',
    'During our leadership speaker event, Dr. Sharon Feng spoke about leadership and the prominence, or lack thereof, of Asian leaders within the professional area. Dr. Sharon Feng is the Global Director of Science and Technology at PPG Industries, one of the world’s largest coating companies. In her...',
    1,
    $content$[{"type":"paragraph","text":"During our leadership speaker event, Dr. Sharon Feng spoke about leadership and the prominence, or lack thereof, of Asian leaders within the professional area. Dr. Sharon Feng is the Global Director of Science and Technology at PPG Industries, one of the world’s largest coating companies. In her current role, she leads the global flagship R&D center in Pittsburgh with more than 300 scientists as well as analytical science laboratories across the globe. Since 2009, she has been a member of the board of directors for Koppers, a carbon material company, and serves as the chair of the Sustainability Committee on the board."},{"type":"paragraph","text":"Before joining PPG, Dr. Feng was the Senior Associate Dean of the School of Molecular Engineering at the University of Chicago. Before that, she had more than 20 years of leadership experience in material and biotech industries with roles in R&D, marketing, business development and various corporate functions. She received her Ph.D. in chemistry from MIT."},{"type":"paragraph","text":"Throughout her speech, Dr. Feng delineated that leadership is not about improving oneself, but making others better. This distinction separates them from bosses, who manage and delegate rather than inspire. Instead of simply handing out tasks and deadlines, a leader also communicates to their underlings the purpose of their work. Through this process, people become motivated and work more passionately. Because of this, leaders don’t necessarily need people to report to them. Additionally, leaders don’t emphasize the hierarchical structure that managers abide by. In fact, leadership itself isn’t a position, but an action."},{"type":"paragraph","text":"Dr. Feng also addressed the “bamboo ceiling”, which refers to the barriers that prevent Asians and Asian Americans from reading executive positions. Currently, only 2% of Fortune 500 companies’ CEOs are Asian. Some potential barriers those of Asian descent may face include a lack of self advocacy, a reserved nature, or inability to adapt. But at the same time, that same Asian heritage enables passion, self discipline, perseverance, humbleness, and resilience. These qualities are what are needed to surpass the bamboo ceiling and reach those higher-up positions."},{"type":"paragraph","text":"By knowing yourselves and playing to your strengths, anyone can become a leader. To become a leader, you need to learn with imperfection. An 80% success rate is good enough, so there’s no need to chase perfection. Leadership opportunities are everywhere, so it is up to us to seek out and find these opportunities. This begins with networking and building connections, so that opportunities naturally find you."}]$content$::jsonb,
    'local',
    'images/blog/leadership-speaker-event-cover.avif',
    'Leadership Speaker Event',
    'published',
    null,
    'Darren Wang',
    '2022-08-15T01:16:21.738Z'::timestamptz,
    '2022-08-15T01:16:21.738Z'::timestamptz,
    '2022-08-15T01:16:21.738Z'::timestamptz
),
(
    'open-house-event',
    'PCA Open House Event',
    'In the PCA student council, we have always put a heavy emphasis on fostering young aspiring students and providing opportunities for enrichment. As such, the PCA recently held an Open House event, where students with a passion for community service joined the student council for a fun and informa...',
    1,
    $content$[{"type":"paragraph","text":"In the PCA student council, we have always put a heavy emphasis on fostering young aspiring students and providing opportunities for enrichment. As such, the PCA recently held an Open House event, where students with a passion for community service joined the student council for a fun and informative evening."},{"type":"paragraph","text":"Around 20 kids participated, with students ranging from grade 7 to 11. Through a series of activities such as the name game, students were able to learn about how the student council works, our values, and the impact we have on the local community."},{"type":"paragraph","text":"Moving forward, the student council hopes to continue to inspire students to volunteer and work towards bettering our community. Additionally, we look forward to formally welcoming these new students into the PCA."}]$content$::jsonb,
    'local',
    'images/blog/open-house-event-cover.avif',
    'PCA Open House Event',
    'published',
    null,
    'Darren Wang',
    '2022-08-01T01:20:04.652Z'::timestamptz,
    '2022-08-01T01:20:04.652Z'::timestamptz,
    '2022-08-01T01:20:04.652Z'::timestamptz
),
(
    'year-in-review',
    'Year In Review',
    'In the past few months, the PCA Student Council has held a wide variety of fun and engaging events, amounting to a wildly successful year. Each student council member was indispensable in the designing and execution of these events.',
    1,
    $content$[{"type":"paragraph","text":"In the past few months, the PCA Student Council has held a wide variety of fun and engaging events, amounting to a wildly successful year. Each student council member was indispensable in the designing and execution of these events."},{"type":"paragraph","text":"With the coronavirus still prevalent in earlier months, the student council adapted by hosting an online escape room and virtual seminars. Through these events, we achieved our goals of providing opportunities for fun and education for the community while also maintaining safety. The council also organized a series of coding workshops, which attracted many young aspiring students excited to learn and explore."},{"type":"paragraph","text":"All of our work culminated in the AAPI Heritage Month Book Drive and our summer field day. The book drive was a large-scale event set across multiple school districts. With help from donors and sponsors, the student council was able to raise nearly $3,000 for books with authors of Asian heritage. In contrast, the summer field day was focused on helping kids experience the joy of summer and make worthwhile social connections."},{"type":"paragraph","text":"The student council was also committed to the greater Pittsburgh community, volunteering with other organizations to distribute food and plant trees around Pittsburgh. These events also drew in other volunteers outside of the student council who were still trying to make an impact. We also heavily collaborated with the Ronald McDonald House Charities in order to provide for those in need."},{"type":"paragraph","text":"The student council was also active in spreading culture through participation in the Pittsburgh Chinese Cultural Festival and Pittsburgh’s Historic Chinatown Celebration."},{"type":"paragraph","text":"We hope future events will be able to reach even more people and provide greater opportunity for growth, enrichment, and fun."}]$content$::jsonb,
    'local',
    'images/blog/year-in-review-cover.avif',
    'Year In Review',
    'published',
    null,
    'Darren Wang',
    '2022-07-18T01:54:47.987Z'::timestamptz,
    '2022-07-18T01:54:47.987Z'::timestamptz,
    '2022-07-18T01:54:47.987Z'::timestamptz
),
(
    'summer-field-day',
    'Summer Field Day!',
    'To celebrate the coming of summer, the PCA Student Council organized a fun and exciting field day event, with 30 kids participating.',
    1,
    $content$[{"type":"paragraph","text":"To celebrate the coming of summer, the PCA Student Council organized a fun and exciting field day event, with 30 kids participating."},{"type":"paragraph","text":"The eventful afternoon commenced with three rounds of diverse stations, each of which captured the kids’ attention in a different way. These stations included cup pong, relay tic-tac-toe, and sharks and minnows. As the kids rotated from station to station, boisterous laughter and cheering could be heard throughout."},{"type":"paragraph","text":"After the stations had wrapped up and the kids were all re-energized by a quick snack break, we moved on to our big group events. Among the games were limbo, tug-of-war, and capture the flag. Each game was intense, with everyone zealously competing against each other. However, during tug-of-war, some kids were hurt due to their enthusiasm. As an organization with a commitment to safety, the PCA Student Council recognizes any faults. We are always trying to improve upon our mistakes. We believe that this experience will allow us to prevent any such injury from occurring at any future PCA event."},{"type":"paragraph","text":"Afterwards, the exhilarating day came to a finale with a huge water fight, complete with water balloons and guns. The kids particularly enjoyed this event, with many labeling it as their favorite."},{"type":"paragraph","text":"Overall, the day was a huge success, as the kids were able to experience the joy of summer together. We received overwhelmingly positive reception from parents and kids alike."},{"type":"paragraph","text":"Lastly, we would like to celebrate the student council members that won Presidential Awards this year. We hope that their leadership and hard work will continue to inspire others and foster growth within our community!"}]$content$::jsonb,
    'local',
    'images/blog/summer-field-day-cover.avif',
    'Summer Field Day!',
    'published',
    null,
    'Darren Wang',
    '2022-06-20T01:51:09.166Z'::timestamptz,
    '2022-06-20T01:51:09.166Z'::timestamptz,
    '2022-06-20T01:51:09.166Z'::timestamptz
),
(
    'tree-planting-event',
    'Tree Planting Event!',
    'With Spring in full bloom, the PCA Youth Center organized and participated in a tree planting event hosted by the Western Pennsylvania Conservatory. Together, 20 participants worked diligently to plant a variety of trees along the streets of Point Breeze North.',
    1,
    $content$[{"type":"paragraph","text":"With Spring in full bloom, the PCA Youth Center organized and participated in a tree planting event hosted by the Western Pennsylvania Conservatory. Together, 20 participants worked diligently to plant a variety of trees along the streets of Point Breeze North."},{"type":"paragraph","text":"Through the planting of Dogwood, red pine, and cherry trees, the PCA Youth Center aims to revitalize the parks and neighborhoods of Pittsburgh while also positively contributing to the environment. Participants were able to learn more about the growing of trees and become more in touch with nature."},{"type":"paragraph","text":"Overall, the event was a major success, receiving all-around positive feedback from the participants. We hope these budding conservationists can serve as an example for others and inspire more environmental action. Lastly, we would like to thank all the participants and organizers for a great event!"}]$content$::jsonb,
    'local',
    'images/blog/tree-planting-event-cover.avif',
    'Tree Planting Event!',
    'published',
    null,
    'Darren Wang',
    '2022-05-02T01:18:48.937Z'::timestamptz,
    '2022-05-02T01:18:48.937Z'::timestamptz,
    '2022-05-02T01:18:48.937Z'::timestamptz
),
(
    'the-new-wave-of-designers-chris-ference',
    'The New Wave of Designers - Chris Ference',
    'This Saturday, PCA hosted a talk called “The New Wave of Designers,” presented by Chris Ference, a designer and experimenter studying Speculative Design at the Rochester Institute of Technology. We had the opportunity to hear about his personal endeavors in speculative design, careers related to...',
    1,
    $content$[{"type":"image","source":"local","path":"images/blog/the-new-wave-of-designers-chris-ference-1.avif","alt":"The New Wave of Designers - Chris Ference photo 1"},{"type":"paragraph","text":"This Saturday, PCA hosted a talk called “The New Wave of Designers,” presented by Chris Ference, a designer and experimenter studying Speculative Design at the Rochester Institute of Technology. We had the opportunity to hear about his personal endeavors in speculative design, careers related to the field, and tips for networking."},{"type":"paragraph","text":"Ference has designed and created many innovations to help individuals in their day-to-day lives and other designers in their work. He showed his previous physical inventions and how he used certain color palettes to create digital graphics. Ference discussed his design process of technical work, along with finding meaning in a creation. He also explained important traits to be a successful designer, like curiosity, open mindedness, and environmental consciousness."},{"type":"paragraph","text":"The process of designing includes brainstorming, research, art design, experimenting, and production. One can experiment with both physical and virtual products for a rewarding end result. This brings to the design table different fields, such as technology, art, and marketing. Ference introduced many careers that are interconnected in the STEAM areas, going further by giving example career paths and summer opportunities. Personally, I found this very informative and helpful for my future, being interested in these topics myself."},{"type":"paragraph","text":"Overall, Chris Ference’s presentation was instructive, visually clear, enjoyable, and especially helpful to those searching for their future career path. If you would like to watch a recording of his talk for yourself, click here! You can also go to Ference’s website to learn more about his work."}]$content$::jsonb,
    'local',
    'images/blog/the-new-wave-of-designers-chris-ference-cover.avif',
    'The New Wave of Designers - Chris Ference',
    'published',
    null,
    'Lina Fu',
    '2022-03-28T01:19:52.176Z'::timestamptz,
    '2022-03-28T01:19:52.176Z'::timestamptz,
    '2022-03-28T01:19:52.176Z'::timestamptz
),
(
    'coding-event-pt-2',
    'Coding Event Pt. 2!',
    'Since the previous coding event we hosted in December was a success, we decided to have another event this March! This time, we had over 40 students getting introduced to new coding topics and expanding on their knowledge through exercises and projects.',
    1,
    $content$[{"type":"paragraph","text":"Since the previous coding event we hosted in December was a success, we decided to have another event this March! This time, we had over 40 students getting introduced to new coding topics and expanding on their knowledge through exercises and projects."},{"type":"paragraph","text":"Our goals, as an organization, include teaching our community and inspiring youth specifically. Technology is a very important field, especially in this day and age, so we wanted to make sure to educate youth. Hopefully, this event brought new minds to the ever growing field."},{"type":"paragraph","text":"We had two groups with about 20 students in each. Students signed up for either Scratch or Python. Aaron Peng and Wilson Chen taught the Scratch group, where they learned how to use block-coding to work on their projects. Some students created a fun chase game using the arrow keys, which the teachers helped out on. The introduction to Python class was taught by Lina Fu (me) and Zoey Guo. Elementary students learned about the basics of Python, including print statements, variables, and loops. At the end of the session, students worked on a final project for a grocery shopping program. As a teacher of this group, I personally enjoyed presenting the new topics to students and collaborating on the exercises. Students in both classes clearly showcased their creativity and newfound coding abilities!"},{"type":"paragraph","text":"Overall, PCA’s coding events have been successful in giving young students opportunities to explore technology. Thank you to our teachers and students for making this event possible!"}]$content$::jsonb,
    'local',
    'images/blog/coding-event-pt-2-cover.avif',
    'Coding Event Pt. 2!',
    'published',
    null,
    'Lina Fu',
    '2022-03-14T01:39:52.994Z'::timestamptz,
    '2022-03-14T01:39:52.994Z'::timestamptz,
    '2022-03-14T01:39:52.994Z'::timestamptz
),
(
    'welcome-new-members',
    'Welcome, New Members!',
    'The PCA student council welcomes its 3 new members, Lina, Rebecca, and Colin! We asked them for a short introduction and why they wanted to join the student council. The replies are below!',
    1,
    $content$[{"type":"paragraph","text":"The PCA student council welcomes its 3 new members, Lina, Rebecca, and Colin! We asked them for a short introduction and why they wanted to join the student council. The replies are below!"},{"type":"paragraph","text":"Lina:"},{"type":"paragraph","text":"\"Hi! I’m Lina, and I’m a junior at North Allegheny. I was interested in joining PCA because I wanted to be a part of the many opportunities it provides to help our community. In my free time, I enjoy baking, reading, and spending time with friends and family!'"},{"type":"paragraph","text":"Colin:"},{"type":"paragraph","text":"\"In general, I’m a pretty active person. I enjoy playing golf and working out at my local gym. I think this part of me also influenced my interest in watching sports. My favorite sports to watch are football, basketball, and hockey. When I saw the opportunity to join the PCA Youth Student Council, I immediately took interest because I was hooked on the idea of joining a team of people around my age to help take part in the process of organizing impactful events. Before joining, I took part in two of these volunteer events, and they made me realize I wanted to contribute in some way.\""},{"type":"paragraph","text":"Rebecca:"},{"type":"paragraph","text":"\"Hi, my name is Rebecca and I'm currently in 8th grade at Marshall Middle School. I enjoy playing the violin and piano, and I swim for Allegheny North Swim Club. I would like to join the student council for the PCA Youth Center because I hope to gain more experience and leadership skills, while also helping others!\""},{"type":"paragraph","text":"Again, welcome to the student council, and we hope you have a meaningful and rewarding experience with us! If you wish to apply, take a look at our about pages. See you in our next event!"}]$content$::jsonb,
    null,
    null,
    null,
    'published',
    null,
    'Aaron Peng',
    '2022-01-31T02:42:12.456Z'::timestamptz,
    '2022-01-31T02:42:12.456Z'::timestamptz,
    '2022-01-31T02:42:12.456Z'::timestamptz
),
(
    'coding-event',
    'Coding event!',
    'As we approach winter, the student council decided to host a highly educational, yet fun learning experience through the coding event! We invited over 30 students to learn and explore varying levels of coding, through challenging activities!',
    1,
    $content$[{"type":"paragraph","text":"As we approach winter, the student council decided to host a highly educational, yet fun learning experience through the coding event! We invited over 30 students to learn and explore varying levels of coding, through challenging activities!"},{"type":"paragraph","text":"The participants were split into two groups depending on their coding experience. Younger students, who have barely touched on the subject were split into the scratch group, learning with MIT’s famous block-coding platform. They were taught by Selena Xiao and Aaron Peng. Older, more experienced students were challenged to create their own discord bot(using Javascript), after seeing an example. Both groups demonstrated exceptional learning abilities, and came up with spectacular results!"},{"type":"paragraph","text":"The event was a large success! We received overwhelming positive feedback from the participants and volunteers. Once again, thank you to our teachers and students for making this event possible, we hope to see you in the next one!"}]$content$::jsonb,
    'local',
    'images/blog/coding-event-cover.avif',
    'Coding event!',
    'published',
    null,
    'Aaron Peng',
    '2022-01-03T02:36:40.069Z'::timestamptz,
    '2022-01-03T02:36:40.069Z'::timestamptz,
    '2022-01-03T02:36:40.069Z'::timestamptz
),
(
    'pca-meditation-event',
    'PCA Meditation Event',
    'The student council recently hosted a meditation event where we invited psychology student Eric Chen to share his experience with meditation, how it positively impacted his life, and how he started a meditation group in his high school. The event was largely successful, with over 20 participants...',
    1,
    $content$[{"type":"image","source":"local","path":"images/blog/pca-meditation-event-1.avif","alt":"PCA Meditation Event photo 1"},{"type":"paragraph","text":"The student council recently hosted a meditation event where we invited psychology student Eric Chen to share his experience with meditation, how it positively impacted his life, and how he started a meditation group in his high school. The event was largely successful, with over 20 participants of parents and students alike!"},{"type":"paragraph","text":"Eric opened by discussing how meditation had personally impacted his life and his peers. He emphasized how meditation was highly beneficial both to his academic performance and emotional wellbeing, especially during the pandemic. Meditating for even only 20 minutes each day still had significant stress relieving effects."},{"type":"paragraph","text":"Inspired by his own personal gains, Eric decided to open a meditation group in his high school for anyone consumed by stress. He received overwhelmingly positive feedback, and many members of the group reported higher overall happiness."},{"type":"paragraph","text":"His instruction was very helpful and informative. After first running through the basics of meditation, including its benefits and how it is performed, Eric walked us through a 10 minute meditation session. Throughout his presentation, mindfulness was brought up a number of times. Mindfulness is closely tied with meditation, which is the state of being more aware and focused on the present, rather than thinking about the past or future."},{"type":"paragraph","text":"Thank you to Eric and everyone else who attended our event; if you missed this one, make sure to stop by and check out our coding workshop in December!"},{"type":"paragraph","text":"- PCA Student Council"}]$content$::jsonb,
    'local',
    'images/blog/pca-meditation-event-cover.avif',
    'PCA Meditation Event',
    'published',
    null,
    'PCA Website and Blog Team',
    '2021-12-13T02:37:37.350Z'::timestamptz,
    '2021-12-13T02:37:37.350Z'::timestamptz,
    '2021-12-13T02:37:37.350Z'::timestamptz
),
(
    'presidential-awards',
    'Presidential Awards!',
    'Congratulations to the student council members from 2019-2021 for their hard work! The PCA Youth center held an award distributing event, where all members who got 50+ hours in a year within 2019-2021 received an award!',
    1,
    $content$[{"type":"paragraph","text":"Congratulations to the student council members from 2019-2021 for their hard work! The PCA Youth center held an award distributing event, where all members who got 50+ hours in a year within 2019-2021 received an award!"},{"type":"image","source":"local","path":"images/blog/presidential-awards-1.avif","alt":"Presidential Awards! photo 1"},{"type":"image","source":"local","path":"images/blog/presidential-awards-2.avif","alt":"Presidential Awards! photo 2"},{"type":"image","source":"local","path":"images/blog/presidential-awards-3.avif","alt":"Presidential Awards! photo 3"},{"type":"image","source":"local","path":"images/blog/presidential-awards-4.avif","alt":"Presidential Awards! photo 4"},{"type":"image","source":"local","path":"images/blog/presidential-awards-5.avif","alt":"Presidential Awards! photo 5"},{"type":"image","source":"local","path":"images/blog/presidential-awards-6.avif","alt":"Presidential Awards! photo 6"}]$content$::jsonb,
    'local',
    'images/blog/presidential-awards-cover.avif',
    'Presidential Awards!',
    'published',
    null,
    'Aaron Peng',
    '2021-11-20T02:59:48.187Z'::timestamptz,
    '2021-11-20T02:59:48.187Z'::timestamptz,
    '2021-11-20T02:59:48.187Z'::timestamptz
),
(
    'breakout-room-v-2',
    'Breakout Room V.2!',
    'Amidst a tough transition period during which students struggle to adapt to the busier, more hectic life of school, the PCA student council elected to create an educational breakout room to allow kids to learn in a more casual, interactive environment. Our event was very successful, with 40 stude...',
    1,
    $content$[{"type":"paragraph","text":"Amidst a tough transition period during which students struggle to adapt to the busier, more hectic life of school, the PCA student council elected to create an educational breakout room to allow kids to learn in a more casual, interactive environment. Our event was very successful, with 40 students ranging from 1st to 8th grade attending our breakout sessions through Zoom."},{"type":"paragraph","text":"The PCA student council met up each week for 5 weeks and worked earnestly under the supervision of the presidents, Sophia Liao and Edward Mei, and counselor YiFei Zhao. Groups of 4-6 were quickly and efficiently organized to effectively work on the escape room. Each member was given opportunities to brainstorm ideas, contribute, and give constructive feedback. Additionally, members played to their strengths, ensuring that each aspect of the event was polished to the absolute maximum. What resulted was a conglomeration of separate concepts and ideas that fit together to make a comprehensive escape room."},{"type":"paragraph","text":"Our breakout room utilized available technology resources to its full potential, allowing us to incorporate educational themes into all sorts of complex puzzles. Through these challenges, we were able to educate participants on the signing of the Declaration of Independence and the origins of America. Additionally, by placing participants in separate groups, they were able to learn about teamwork and problem solving skills. Most importantly, we made the entire process intriguing and fun, capturing the attention of participants. As this was our first event with new student council members, this was a learning opportunity for us too. As each of us navigated through the processes of working together, we learned to build on each other's ideas in a cumulative manner. As such, this event was an opportunity not only for young kids, but also the PCA student council to explore the intricacies and nuances of cooperating and leading in a group setting with kids of varying ages."},{"type":"paragraph","text":"As the event on Zoom began, I was greeted by a wall of smiling faces, all of them eager to learn and explore what we had in store. After they were split into predetermined groups, they set off on their adventure, enraptured by the captivating story and intricate puzzles. As they progressed through the rooms, I was able to witness the thought process and development of my group in real time. It was very rewarding to see their gradual advancement into truly working as a team. It was also extremely gratifying to see my group’s beaming faces when they completed the challenge, all of them elated by their success."},{"type":"paragraph","text":"Overall, this event was a great success, receiving positive reception from both students and parents alike. We were also able to procure much needed advice and insight into how to further improve and refine our future events. Each and every one of our members put in their utmost effort to realize our plans, with many putting in extra hours, so we would like to thank them for their diligence and commitment. Our members are already beginning to structure a new event, this time even more exciting than the last, so stay alert for any news on upcoming events!"}]$content$::jsonb,
    'local',
    'images/blog/breakout-room-v-2-cover.avif',
    'Breakout Room V.2!',
    'published',
    null,
    'Darren Wang',
    '2021-10-18T01:14:23.591Z'::timestamptz,
    '2021-10-18T01:14:23.591Z'::timestamptz,
    '2021-10-18T01:14:23.591Z'::timestamptz
),
(
    'career-exploration',
    'Career Exploration',
    'As the middle of summer has arrived and is quickly passing by, we begin to think about and look forward to what the future holds. Summer is the perfect time and season to explore and develop new interests. As always, the PCA Student Council strives to create opportunities for our community to gro...',
    1,
    $content$[{"type":"paragraph","text":"As the middle of summer has arrived and is quickly passing by, we begin to think about and look forward to what the future holds. Summer is the perfect time and season to explore and develop new interests. As always, the PCA Student Council strives to create opportunities for our community to grow and develop. This time, we decided to dive deep into an extensive subject that may be intimidating or confusing to the minds of the youth: careers. By inviting 12 professional speakers across a diverse range of careers, we hoped to inspire interest and foster an introduction in our youth to the endless world of careers."},{"type":"paragraph","text":"PCA Youth Center held a series of Career Exploration Events over the course of the last few months (May 24th, June 19th, and June 26th, 2021) via Zoom, inviting speakers from all over the country with a wide variety of professions. We were honored to have Lauren Corcoran Emrich (vocal teacher and professional singer), Brad Shiying Si (director of risk management department), Jessica Wang (software engineer), Jennifer Lin (pharmacist), Scott Mao (professor), Yuhui Wang (financial analyst), Nathan Grealish (UX designer), Yan Lin & Ying Ding (biostatistics professors), Natalie David (veterinarian), Shuangshuang Li (UX designer), Dr. Wei Sun (cardiologist) as our guest speakers. Our participants were of all ages, and we had a peak of 103!"},{"type":"paragraph","text":"Each speaker prepared a 15-20 minute presentation regarding their careers as well as the steps they took to achieve their success. There was a short Q/A session at the end of each speech so that our participants had the opportunity to ask their own questions. Overall, the events were very engaging and there were so many memorable moments! Ms. Lauren Emrich sang a beautiful operetta, bringing her talent to this event and showing her passion for music through the lively piece. Mr. Brad Si spoke of his impressive experiences in the field of risk management while working at some of the top companies in the US, ranging from Morgan Stanley located in the financial district on Wall Street to the well-known BNY Mellon banking company. Ms. Jessica Wang gave very helpful advice on becoming a software engineer through her light-hearted and relatable speech. Ms. Jennifer Lin spoke about her profession as a pharmacist, as well as which majors and medical/health-related requisites would be beneficial to working in a pharmacy. Mr. Scott Mao, who is a material science professor at the University of Pittsburgh, talked about the many job opportunities one can get while majoring in material science, as well as broadening our horizons on this subject. Ms. Yuhui Wang explained the daily life of being a financial analyst and the work she is responsible for to satisfy each client’s needs. 2 UX designers, Mr. Nathan Grealish and Ms. Shuangshuang Li each told us their stories after graduating college with a major in graphic arts and computer science respectively, all the way to their current job as a UX designer. Ms. Yan Lin and Ms. Ying Ding shared their experiences of being biostatistics professors at the University of Pittsburgh and gave us compelling background information on what statistics and other health sciences are. Ms. Natalie David, a veterinarian, shared her story which encompassed the life and death experience one has to go through while being a vet. Healing injured animals could always go both ways, and her inspiring presentation left us all thinking about what survival really means. Finally, through this event, we got to see a “day in the life” of a cardiologist (Dr. Wei Sun), and how he, among millions of other doctors, saves people’s lives every day by directly witnessing humanity at its best and worst and dedicating their own life to the study of medicine and healing."},{"type":"paragraph","text":"The 3 Days were recorded, and are uploaded on YouTube through our PCA channel. Links are attached here:"},{"type":"paragraph","text":"Day 1: https://www.youtube.com/watch?v=0YeUCVYTGGs"},{"type":"paragraph","text":"Day 2: https://www.youtube.com/watch?v=5adP0Vfo24I"},{"type":"paragraph","text":"Day 3: https://www.youtube.com/watch?v=lWhGotgXCZA&t"},{"type":"paragraph","text":"Thank you to the student council (Yi-Fei, Kevin, Chennie, Selena, Hannah, Iris, Edward, Aaron, Sophia, and Matt), the counselors (Crystal, Amy, and Jefferson), and the parents"},{"type":"paragraph","text":"for making this event come true. Thank you to our wonderful guest speakers for giving such inspirational speeches and sharing your stories with us. We highly appreciate your hard work and dedication to this event, and we were so honored to have you. PCA would also like to express our thanks to all our participants. We hope you enjoyed this series of career exploration events! The council is already preparing for our next event, so please stay tuned and look forward to it!"}]$content$::jsonb,
    'local',
    'images/blog/career-exploration-cover.avif',
    'Career Exploration',
    'published',
    null,
    'Chennie Wang and Hannah Song',
    '2021-07-29T17:28:29.177Z'::timestamptz,
    '2021-07-29T17:28:29.177Z'::timestamptz,
    '2021-07-29T17:28:29.177Z'::timestamptz
),
(
    'lunar-new-year-event',
    'Lunar New Year Event',
    'The Lunar New Year is one of the most important holidays in Chinese culture. Tied to the Lunar Calendar, rather than the Gregorian Calendar, the holiday is traditionally a time to greet the New Year and to bring families together for feasting. This year, the COVID-19 pandemic has affected communi...',
    1,
    $content$[{"type":"paragraph","text":"The Lunar New Year is one of the most important holidays in Chinese culture. Tied to the Lunar Calendar, rather than the Gregorian Calendar, the holiday is traditionally a time to greet the New Year and to bring families together for feasting. This year, the COVID-19 pandemic has affected communities and celebrations all around the world, making it difficult for people to gather for the annual Lunar New Year. Here at PCA, we’ve been working to bring our community together, even if it isn’t in person."},{"type":"paragraph","text":"On February 14th, we held our Lunar New Year PCA Event, consisting of 3 different stations: Spin the Wheel Dancing, Origami, and Chinese Paper Cutting. I co-hosted the Dancing station along with Selena Xiao, a PCA Student Council Member, and it was extremely successful! Participants for this station ranged from Kindergarteners to 7th graders! After generating a list with the names of participants, they would do randomized dancing dares such as “do your favorite dance move” or “choreograph a 10-second dance”. The station was filled with laughter, and I loved seeing the kids step out of their comfort zone to try out new things!"},{"type":"image","source":"local","path":"images/blog/lunar-new-year-event-1.avif","alt":"Lunar New Year Event photo 1"},{"type":"paragraph","text":"The origami station was organized by Kevin Mao (PCA Student Council Co-President) and Edward Mei (PCA Student Council Co-Vice President). Kevin and Edward showed participants how to make an origami ox, in honor of this year’s Chinese zodiac. The finished product was very impressive, and the kids had so much fun making it!"},{"type":"image","source":"local","path":"images/blog/lunar-new-year-event-2.avif","alt":"Lunar New Year Event photo 2"},{"type":"image","source":"local","path":"images/blog/lunar-new-year-event-3.avif","alt":"Lunar New Year Event photo 3"},{"type":"paragraph","text":"The paper cutting station was hosted by Sophia Liao (PCA Student Council Co-Vice President) and Elaine Liao (her sister). They taught participants how to make an ox using Chinese paper cutting, which is a traditional type of folk art in China."},{"type":"image","source":"local","path":"images/blog/lunar-new-year-event-4.avif","alt":"Lunar New Year Event photo 4"},{"type":"paragraph","text":"Thank you to the student council (Yi-Fei, Kevin, Chennie, Selena, Hannah, Iris, Edward, Aaron, Sophia, and Matt), the counselors (Crystal, Amy, and Jefferson), for all your hard work in this event. We would also like to express our appreciation to all participants, past and present, who always support and participate in our events. We hope you enjoyed this event! The council is already working hard to discuss new ideas for future events, so please stay tuned for them, as we would love to have you here!"},{"type":"image","source":"local","path":"images/blog/lunar-new-year-event-5.avif","alt":"Lunar New Year Event photo 5"},{"type":"image","source":"local","path":"images/blog/lunar-new-year-event-6.avif","alt":"Lunar New Year Event photo 6"}]$content$::jsonb,
    'local',
    'images/blog/lunar-new-year-event-cover.avif',
    'Lunar New Year Event',
    'published',
    null,
    'Chennie Wang',
    '2021-02-22T03:07:30.912Z'::timestamptz,
    '2021-02-22T03:07:30.912Z'::timestamptz,
    '2021-02-22T03:07:30.912Z'::timestamptz
),
(
    'shining-thru-the-holidays',
    'Shining Thru the Holidays',
    'The COVID-19 pandemic has made it difficult for everyone to celebrate the holidays like other years. However, at PCA Youth Center, we were still able to connect with our community and celebrate through holding a holiday lights show!',
    1,
    $content$[{"type":"paragraph","text":"The COVID-19 pandemic has made it difficult for everyone to celebrate the holidays like other years. However, at PCA Youth Center, we were still able to connect with our community and celebrate through holding a holiday lights show!"},{"type":"paragraph","text":"From December 11th to January 3rd, we held our Shining Thru The Holidays event, which allowed participants to share their holiday decorations with others! They took pictures of holiday decorations around their home, including but not limited to DIY decorations, festive rooms, or brightly lit yards. The pictures were then entered in a survey in which participants and their friends voted on pictures based on three categories: Creativity, Popularity, and Overall Festivity! Each category winner was awarded a $30 Amazon gift card!"},{"type":"paragraph","text":"The top photo from each of the three categories was voted on by our community. With submissions from participants of all ages, we received a total of 68 photos ranging from festively decorated Christmas trees to self-made holiday related arts and crafts pieces to city scenes. All submissions can be found under the Gallery tab of our website. Feel free to check out the creative and festive photos taken by our participants!"},{"type":"paragraph","text":"Thank you to all who participated, the student council (Yi-Fei, Kevin, Alicia, Matthew, Chennie, Hannah, Sophia, Edward, Aaron, Iris), the counselors (Amy and Jefferson), and the parents for their time and efforts. Please feel free to reach out to any of the members listed on our website to ask questions, and stay updated for our future events. We hope to see you there!"}]$content$::jsonb,
    'local',
    'images/blog/shining-thru-the-holidays-cover.avif',
    'Shining Thru the Holidays',
    'published',
    null,
    'Chennie Wang',
    '2021-02-03T19:25:49.977Z'::timestamptz,
    '2021-02-03T19:25:49.977Z'::timestamptz,
    '2021-02-03T19:25:49.977Z'::timestamptz
),
(
    'seizing-the-last-moments-of-2020',
    'Seizing the Last Moments of 2020',
    '2020— a year like no other — has finally said goodbye as we welcome 2021, who greets us with a new year full of possibilities, opportunities, and hope. Due to the current circumstances, many things have changed, such as the ways in which we could give back to and support our community. At PCA You...',
    1,
    $content$[{"type":"paragraph","text":"2020— a year like no other — has finally said goodbye as we welcome 2021, who greets us with a new year full of possibilities, opportunities, and hope. Due to the current circumstances, many things have changed, such as the ways in which we could give back to and support our community. At PCA Youth Center, we were still able to connect with our community through holding a variety of online projects, such as online escape rooms, trivia, seminars, and most recently, a photography show!"},{"type":"paragraph","text":"On November 9th, we held our Snapshot event, which was a photography seminar held by Dr. Min Sun. After the seminar, we encouraged participants to utilize their new knowledge and skills from the seminar by taking photos. Creativity, color, and beauty can be found in every corner of our world and a great way to express them is through photography. During these rough and uncertain times, it can be healing and comforting to capture a beautiful moment of our lives, whether it be inside our houses or outside in a local park."},{"type":"paragraph","text":"Our photography show was divided into four categories: light, holidays, animals, and nature. The top photos from each of the four categories were selected by our judges, Mr. Xu Jian and Mr. Zhou Xin. With submissions from participants ages of 9-16, we received a total of 45 photos ranging from nature in local parks to indoor holiday decorations and celebrations. All submissions can be found under the Gallery tab of our website. Feel free to check out the diverse and beautiful photos taken by our community!"},{"type":"paragraph","text":"Thank you to all who participated and a big shout out to our judges Mr. Xu Jian and Mr. Zhou Xin for their valuable thoughts, feedback, and time. Thank you to our student council (Crystal, Yi-Fei, Kevin, Alicia, Matthew, Chennie, Hannah, Sophia, Edward, Aaron, Iris), the counselors (Amy and Jefferson), and the parents for their time and efforts. We enjoyed creating and holding this event and we hope all our participants also enjoyed the experience."},{"type":"paragraph","text":"We are looking forward to another wonderful year with everyone! We will continue to better our events so that they will fill your year with many fun and memorable experiences. Happy new year everyone, see you soon!"}]$content$::jsonb,
    'local',
    'images/blog/seizing-the-last-moments-of-2020-cover.avif',
    'Seizing the Last Moments of 2020',
    'published',
    null,
    'Hannah Song',
    '2021-01-15T14:49:26.418Z'::timestamptz,
    '2021-01-15T14:49:26.418Z'::timestamptz,
    '2021-01-15T14:49:26.418Z'::timestamptz
),
(
    'capturing-every-moment-picture-by-picture',
    'Capturing Every Moment, Picture by Picture',
    'What better way is there to celebrate Autumn than going outside to capture some fall aesthetic photos? November is in the midst of the Fall season, and it’s just the right time to discover a new hobby of photography. Here at PCA, we hosted a Photography Seminar led by Dr. Min Sun, an oncologist....',
    1,
    $content$[{"type":"image","source":"local","path":"images/blog/capturing-every-moment-picture-by-picture-1.avif","alt":"Capturing Every Moment, Picture by Picture photo 1"},{"type":"paragraph","text":"What better way is there to celebrate Autumn than going outside to capture some fall aesthetic photos? November is in the midst of the Fall season, and it’s just the right time to discover a new hobby of photography. Here at PCA, we hosted a Photography Seminar led by Dr. Min Sun, an oncologist. As an avid enthusiast of photography, Dr. Sun started his avocation at the young age of 8 and completed many works. Some of his projects include photos of wild animals, nature, sports, and people. Although he enjoys all sorts of photography, his favorite style is street photography, which is capturing chance serendipities in public places."},{"type":"paragraph","text":"SnapShot took place on November 7th via Zoom. The event proved to be very successful, as we had approximately 40 participants ranging from 2nd-8th grade- and parents. During the seminar, Dr. Sun spoke about the various types of digital cameras, the most suitable time to take photos, the rule of thirds, subjected background colors, and other photography tips. He also introduced his first camera, a 2 lens Seagull camera, and his second camera- a Seagull DF-1. Participants explored the wonders of photography through Dr. Sun’s showcase of extraordinary photos. His explanations were in great detail, and it was really captivating to see how there is so much thought and effort behind each click of the camera! As Dr. Sun said, photography isn’t about perfection. It’s about capturing the moment, picture by picture, and, more importantly, enjoying this beautiful form of art!"},{"type":"paragraph","text":"A huge thank you so much to Dr. Sun for this wonderful seminar! Thank you to the student council (Yi-Fei, Kevin, Chennie, Selena, Hannah, Iris, Edward, Aaron, Sophia, Alicia, and Matt), the counselors (Crystal, Amy, and Jefferson), for all your hard work in this event. We would also like to recognize the parents and adult council for the countless hours you put into this. Lastly, we express our appreciation to all participants, past and present, who always support and participate in our events. We hope you enjoyed this seminar and acquired a few things about photography (and maybe discovered a new area of interest!). The council is already working hard to discuss new ideas for future events, so please stay tuned for them, as we would love to have you here!"},{"type":"paragraph","text":"We look forward to seeing everyone very soon, and, in the meantime, please stay safe during these challenging circumstances! If you have any questions or concerns, feel free to contact any of the council members listed on our website!"}]$content$::jsonb,
    'local',
    'images/blog/capturing-every-moment-picture-by-picture-cover.avif',
    'Capturing Every Moment, Picture by Picture',
    'published',
    null,
    'Chennie Wang',
    '2020-11-10T02:22:26.675Z'::timestamptz,
    '2020-11-10T02:22:26.675Z'::timestamptz,
    '2020-11-10T02:22:26.675Z'::timestamptz
),
(
    'lost-in-time',
    'Lost in Time',
    'Editor: Hannah Song',
    1,
    $content$[{"type":"paragraph","text":"Editor: Hannah Song"},{"type":"paragraph","text":"A few months ago, our PCA Student Council held our first virtual escape room. We received a lot of great feedback and many participants were super enthusiastic about the idea of another escape room. Because of this, the PCA Student Council had decided to host another virtual escape room."},{"type":"paragraph","text":"This time, the theme was “Lost in Time.” The participants discovered an old compass, which transferred them far into the past. They had to fix the compass in order to try to get back to the present time. In order to fix a part of the compass, the participants had to pass through different rooms, each with a designated time period. Through each room, they learned about significant events that happened in the past, ranging from the Tang dynasty all the way to America’s Roaring 20s!"},{"type":"paragraph","text":"Our second escape room took place on September 6 over Zoom and over 50 participants attended the event, which was even more participants than last time! They ranged from 3rd grade all the way to 7th grade. The kids were all eager to start and worked well within their teams. Overall the event was successful and fun for the participants and the council! We hope all the participants learned something and had fun! We are already planning our next event so stay tuned!"}]$content$::jsonb,
    'local',
    'images/blog/lost-in-time-cover.avif',
    'Lost in Time',
    'published',
    null,
    'Sophia Liao',
    '2020-10-05T01:14:18.007Z'::timestamptz,
    '2020-10-05T01:14:18.007Z'::timestamptz,
    '2020-10-05T01:14:18.007Z'::timestamptz
),
(
    'a-night-of-virtual-trivia',
    'A Night of Virtual Trivia',
    'Time really does fly as the end of summer rapidly approaches! I’m sure we’ve all reflected on how the global pandemic inevitably impacted our lives this summer and how it will continue to in the uncertain future. However, one thing that we do know for certain is that here, at PCA, we will continu...',
    1,
    $content$[{"type":"paragraph","text":"Time really does fly as the end of summer rapidly approaches! I’m sure we’ve all reflected on how the global pandemic inevitably impacted our lives this summer and how it will continue to in the uncertain future. However, one thing that we do know for certain is that here, at PCA, we will continue to support our communities and strengthen our outreach in any way we can during these circumstances--- we’re in this together. Because our interactions are somewhat limited due to the circumstances of the pandemic, we hope to connect and unite our communities through our online events. It is extremely important, especially during these times, to create and encourage more opportunities to support, communicate, and interact with each other."},{"type":"paragraph","text":"After the success of our first Escape room online event and our ongoing Youtuber events, our student council was eager to plan another virtual event. After careful discussion and consideration, we decided to host an online trivia event. Our vision was to provide kids with an opportunity to learn some interesting new facts while interacting with others in a friendly but competitive online environment. We asked trivia questions based on topics including math, history, science, literature, and random facts. Each team would have the opportunity to challenge every other team and the team ending with the most points would win."},{"type":"paragraph","text":"On August 1, we held the event on Zoom. The turnout was fantastic- we had around 40 participants ranging from 2nd-7th grade. The participants were divided into teams of 4-6 based on age. Two student council members were assigned to each breakout room and every team would move through each breakout room and get quizzed on a different topic. As a student council member, I was in charge of a breakout room with my fellow council members Sophia and Aaron. As each team faced off, it was so refreshing to watch the kids participate with such a high level of enthusiasm! Each team displayed teamwork skills and collaborated with such an encouraging spirit. Their enthusiasm was contagious and I felt this event was very enjoyable for both the kids and our council members!"},{"type":"paragraph","text":"Thank you to our past and present participants who support and participate in our events. Behind the scenes, our student council members and parents put a lot of time and effort to make our events run smoothly and enjoyably. Thank you to our student council (Crystal, Yi-Fei, Kevin, Alicia, Matthew, Chennie, Hannah, Sophia, Edward, Aaron, Iris), the counselors (Amy and Jefferson), and the parents for their countless time and efforts."},{"type":"paragraph","text":"With the conclusion of last weekend’s trivia event, we have now successfully held so many online events during this pandemic. Each event is so well received that it drives us to plan more exciting and fun events. To all of our participants- we hope you enjoyed our trivia event! We are already discussing new ideas for our next events, so make sure to stay tuned! We wish you all to stay healthy and safe during these times and look forward to seeing you very soon!"}]$content$::jsonb,
    'local',
    'images/blog/a-night-of-virtual-trivia-cover.avif',
    'A Night of Virtual Trivia',
    'published',
    null,
    'Hannah Song',
    '2020-08-06T16:29:36.229Z'::timestamptz,
    '2020-08-06T16:29:36.229Z'::timestamptz,
    '2020-08-06T16:29:36.229Z'::timestamptz
),
(
    'a-journey-of-motivation',
    'A Journey of Motivation',
    'For the past few months, we have been staying inside and trying to stay productive through these difficult times. The current situation of COVID-19 has taught us many lessons through the good and the bad, such as endurance and perseverance. Quarantine amidst this global pandemic can be viewed as...',
    1,
    $content$[{"type":"paragraph","text":"For the past few months, we have been staying inside and trying to stay productive through these difficult times. The current situation of COVID-19 has taught us many lessons through the good and the bad, such as endurance and perseverance. Quarantine amidst this global pandemic can be viewed as a low point, and possibly the bleakest in our lifetime; however, it has become a time to reflect and learn from yourself. Undoubtedly, these times will forever be remembered in our hearts, life must go on. Each person’s journey must continue."},{"type":"image","source":"local","path":"images/blog/a-journey-of-motivation-1.avif","alt":"A Journey of Motivation photo 1"},{"type":"paragraph","text":"On June 20, 2020, the PCA invited two outstanding individuals to talk about their journey through high school, college, and their prospective careers. The first guest, Clytze Sun, is a rising senior at Carnegie Mellon University. She previously lived in China and spoke about her experiences of being an international student. She also gave valuable advice on motivation, self-discipline, and independence. Her main advice to everyone is “to be happy” as she believes strongly that keeping this mindset will allow you to find your passion and do what you enjoy the most. She explained her journey in finding what she loved and how that got her to where she is today. Originally, she loved writing and hoped to pursue a career in creative writing. She even released her own book! However, after taking a few Statistics courses at CMU, she discovered a newfound interest in data science and explored ways to combine her two passions into one. She urged future college students to be open with exploring while keeping a persistent and steady pace towards their goals. Her journey is a truly inspirational one to look up to for all of us mathematically driven students looking to put a creative flair in our careers."},{"type":"image","source":"local","path":"images/blog/a-journey-of-motivation-2.avif","alt":"A Journey of Motivation photo 2"},{"type":"paragraph","text":"The second guest, Tom Bu, is a Yale graduate and will be starting his master’s degree at Carnegie Mellon University this coming fall. He gave important insight into college decisions and making the right choices throughout highschool. He explained his thoughts, personal opinions, and suggestions on college admissions, such as choices for extracurricular activities, the importance of recommendation letters, academic performance, etc. He also introduced everyone to his journey of finding his passion in the biomedical field and deciding to go into the industry after graduating as he believed that it would give him more valuable experience. Tom explained the importance of “setting up step by step goals in order to reach your final vision” in order to accomplish anything. His work and progress are astounding and as a student, I look up to him as a role model and a future example for the direction and path I want to set myself upon."},{"type":"paragraph","text":"Both speakers are amazing examples of the people who work hard to accomplish their goals and push themselves to actively pursue their passions. Their attitudes and mindsets are something that we should all look to. Hopefully, through this panel discussion, we have brought the PCA community yet another opportunity to learn and reflect from one another so that we can continue to grow as individuals and expand as a community."},{"type":"paragraph","text":"A huge thank you to Tom Bu and Clytze Sun for coming to speak and sharing their experiences. Thank you to the adult council for inviting these phenomenal individuals as well as the Student Council for hosting and organizing the event. Lastly, a shout out to our participants who came to listen. Please feel free to stay updated for our future events and we hope to see you there!"}]$content$::jsonb,
    'local',
    'images/blog/a-journey-of-motivation-cover.avif',
    'A Journey of Motivation',
    'published',
    null,
    'Chennie Wang',
    '2020-06-27T02:17:36.215Z'::timestamptz,
    '2020-06-27T02:17:36.215Z'::timestamptz,
    '2020-06-27T02:17:36.215Z'::timestamptz
),
(
    'the-first-month-of-the-online-youtuber-event',
    'PCA Online YouTuber Launch',
    'The circumstances of this global pandemic have propelled everyone to use different ways to connect with one another and find activities to do while stuck at home. Even though we cannot meet in person, the Adult Council and the Student Council have worked to devise a way to bring the PCA community...',
    1,
    $content$[{"type":"paragraph","text":"The circumstances of this global pandemic have propelled everyone to use different ways to connect with one another and find activities to do while stuck at home. Even though we cannot meet in person, the Adult Council and the Student Council have worked to devise a way to bring the PCA community together for something enjoyable, educational, and interactive."},{"type":"paragraph","text":"The program was first introduced by an Adult Council member named Connie Zhao. She proposed the idea of teaching kids various subjects through virtual meetings and called it the Online Youtuber Program. Using Zoom, an online meeting platform, the Student Council, and several volunteers taught classes that range through a plethora of topics, such as exercise, variations of art, and chess. In the first month of testing these online classes, we have learned and worked through the challenges that have surfaced."},{"type":"image","source":"local","path":"images/blog/the-first-month-of-the-online-youtuber-event-1.avif","alt":"PCA Online YouTuber Launch photo 1"},{"type":"paragraph","text":"The PCA started these classes on the week of May 17th. Each class would have a set of dedicated teachers that take time to thoroughly plan their lessons, which last for forty-five minutes. We scattered the courses throughout the week, which allowed participants to sign up for time slots that work best with their schedules. As the lead for the Arts and Crafts classes, I was really nervous when the first lesson rolled around. Thankfully, everyone enjoyed it and looked forward to the next lesson, which was relieving to hear. As the weeks went on, we listened to feedback from the participants and ironed out the kinds of teaching methods that worked best with the students. After running this program for the first month, we hope that the next month will go smoothly."},{"type":"paragraph","text":"Thank you to Connie Zhao for coming up with this idea and leading the program. Thank you to all the teachers that took the time to plan their lessons. Finally, thank you to all the participants that attended these online classes. We hope to see you in future events and classes!"}]$content$::jsonb,
    'local',
    'images/blog/the-first-month-of-the-online-youtuber-event-cover.avif',
    'PCA Online YouTuber Launch',
    'published',
    null,
    'Iris Xia',
    '2020-06-19T17:53:29.756Z'::timestamptz,
    '2020-06-19T17:53:29.756Z'::timestamptz,
    '2020-06-19T17:53:29.756Z'::timestamptz
),
(
    'finding-the-vaccine-in-an-escape-room',
    'Finding the Vaccine in an Escape Room',
    'Amid this global catastrophe, the vast majority of us are going through uncertainties and changes. As a part of a young demographic, online schooling, relying on our phones to communicate with our friends, and not being able to leave our houses are just some of the adaptations we have to make to...',
    1,
    $content$[{"type":"paragraph","text":"Amid this global catastrophe, the vast majority of us are going through uncertainties and changes. As a part of a young demographic, online schooling, relying on our phones to communicate with our friends, and not being able to leave our houses are just some of the adaptations we have to make to our daily lives. However, something that this pandemic cannot and will not take away from us is our sense of community, even if it has to be online. In times like these, it is up to all of us to embrace this pandemic as an opportunity to support each other and strengthen all of us a whole. We're all in this together regardless of our physical distancing."},{"type":"image","source":"local","path":"images/blog/finding-the-vaccine-in-an-escape-room-1.avif","alt":"Finding the Vaccine in an Escape Room photo 1"},{"type":"paragraph","text":"Image Source"},{"type":"paragraph","text":"Here at the PCA Youth Center, we have been exploring and seeking out fun but educational ways to connect with our community virtually. A few weeks ago, our student council came up with the concept to hold an online escape room, and we designed it to be playable for all ages, even adults. Though we could not recreate an actual 3-D room filled with hidden clues, we created a website filled with clues and hints that would take the player through an imaginative storyline instead. The player’s goal is to find the “Coronavirus Vaccine” by finding and solving the clues in each room that are hyperlinked throughout the site. The first team to finish the escape room and find the “vaccine” wins a $40 gift card."},{"type":"paragraph","text":"On May 10, we held the event over Zoom. Around 40 participants (ranging from 2nd graders to adults) signed up, including 2 families. The participants were divided into groups of four, and each student council member was in charge of a group. As a student council member, I was assigned to proctor a group that consisted of four 7th graders. As soon as the meeting started, my computer screen became alive with the smiling and curious faces of the kids! My heart was pumping with excitement to see the kids demonstrate such enthusiasm, despite all of us going through a hard time. The game ran very smoothly and with some hints provided, the kids were able to use their problem-solving skills and teamwork to quickly move through each room until they finally reached the vaccine and escaped! My team actually won the game in the shortest time! It was fascinating to watch them play with such high levels of collaboration and teamwork."},{"type":"paragraph","text":"This online activity organized by our PCA Youth Center was well-received among the participants. Many parents and kids were asking for another similar event. Some of them even said that they couldn’t wait for our next event! I know that behind the scenes, all the PCA student council members and parents put tons of hours of hard work to prepare for this event so it would run meticulously. We had virtual meetings every weekend (and sometimes during the week) to discuss and plan out every detail. We tried out the game many times with the parent council in order to receive feedback to fix and improve our game to make it as enjoyable as possible for the participants. All of it was volunteer work from our members who happily donated their own time, despite their busy schedules. Some were even preparing their AP exams that would take place the following day."},{"type":"paragraph","text":"At the PCA Youth Center, we care deeply for our community and hope to make a positive impact through our events. Thank you to everyone who supported and participated in this and past events. Thank you to the student council (Crystal, Yi-Fei, Kevin, Hannah, Sophia, Edward, Iris, Matthew, Jessica, Aaron), the counselors (Amy and Jefferson), and the parent council for such endless hours of perseverance and teamwork. Big thanks to Yi-Fei, who spent hours designing the escape room website. We are already working hard on our next event, so please stay tuned! We look forward to seeing you all again very soon!"}]$content$::jsonb,
    'local',
    'images/blog/finding-the-vaccine-in-an-escape-room-cover.avif',
    'Finding the Vaccine in an Escape Room',
    'published',
    null,
    'Hannah Song',
    '2020-05-24T02:37:06.544Z'::timestamptz,
    '2020-05-24T02:37:06.544Z'::timestamptz,
    '2020-05-24T02:37:06.544Z'::timestamptz
)
on conflict (slug) do nothing;
